/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mjasinski_tictactoe_engine_Main */

#ifndef _Included_com_mjasinski_tictactoe_engine_Main
#define _Included_com_mjasinski_tictactoe_engine_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mjasinski_tictactoe_engine_Main
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mjasinski_tictactoe_engine_Main_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_mjasinski_tictactoe_engine_Main
 * Method:    randomMove
 * Signature: ([CC)I
 */
JNIEXPORT jint JNICALL Java_com_mjasinski_tictactoe_engine_Main_randomMove
  (JNIEnv *, jobject, jcharArray, jchar);

/*
 * Class:     com_mjasinski_tictactoe_engine_Main
 * Method:    intelligentMove
 * Signature: ([CC)I
 */
JNIEXPORT jint JNICALL Java_com_mjasinski_tictactoe_engine_Main_intelligentMove
  (JNIEnv *, jobject, jcharArray, jchar);

#ifdef __cplusplus
}
#endif
#endif
